import type { Metadata } from "next";
import { Open_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin", "hebrew"],
  weight: ["400", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FotoVoto",
  description: "Generated by create next app",
  icons: {
    icon: "/icon_logo.svg",
  },
  robots: {
    index: true,
    follow: true
  },
  //TODO: Iplementar Open Graph para mejorar la apariencia de los enlaces compartidos en redes sociales
  // openGraph: {
  //   title: "FotoVoto",
  //   description: "Plataforma de votación digital segura",
  //   url: "https://tudominio.com",
  //   siteName: "FotoVoto",
  //   images: [
  //     {
  //       url: "/og-image.png",
  //       width: 1200,
  //       height: 630
  //     }
  //   ],
  //   type: "website"
  // },
  // twitter: {
  //   card: "summary_large_image",
  //   title: "FotoVoto",
  //   description: "Plataforma de votación digital segura y moderna.",
  //   images: ["/og-image.png"]
  // }
  keywords: [
    "FotoVoto",
    "votación digital"
  ],
  //? Configurar en caso de querer verificar la propiedad del sitio con Google Search Console u otros servicios de verificación
  // verification: {
  //   google: "codigo_de_verificacion"
  // }

  //? Configurar en caso de tener un dominio personalizado para evitar problemas de SEO con el dominio de Cloudflare Pages
  // alternates: {
  //   canonical: "https://fotovototest.madridossa.workers.dev"
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montserrat.variable} antialiased flex flex-col min-h-dvh`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
