import type { Metadata } from "next";
import { Open_Sans, Montserrat} from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin", "hebrew"],
  weight: ["400", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${montserrat.variable} antialiased flex flex-col min-h-dvh`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
